version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:9.9.0
    steps:
      # Checkout the code as the first step.
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run: |
          docker login -u ${DIGITALOCEAN_ACCESS_TOKEN} -p ${DIGITALOCEAN_ACCESS_TOKEN} registry.digitalocean.com
          docker build . -t registry.digitalocean.com/wallfair/backend -f Dockerfile.node
          docker push registry.digitalocean.com/wallfair/backend

workflows:
  sample:
    jobs:
      - build