apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../application

namespace: development
commonLabels:
  environment: development


patches:
- configurationPatch.yaml

configMapGenerator:
  - name: backend-config
    behavior: merge
    envs:
      - environment
