apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  template:
    spec:
      containers:
        - name: backend
          envFrom:
          - configMapRef:
              name: backend-config
          - configMapRef:
              name: backend-secrets
          - configMapRef:
              name: app-global-secrets
          - configMapRef:
              name: fractal-secrets
          - configMapRef:
              name: postgres-conn
          - configMapRef:
              name: mongo-conn
          - configMapRef:
              name: redis-conn
          - configMapRef:
              name: rabbit-conn
