apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: backend
spec:
  secretName: backend-cert-secret
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer
  dnsNames:
  - api.alpacasino.io

