# apiVersion: kustomize.config.k8s.io/v1beta1
# kind: Kustomization
resources:
- ../../application
- podDisruptionBudget.yaml
- certificate.yaml

namespace: alpa-prod
commonLabels:
  environment: alpa-prod

configMapGenerator:
  - name: backend-config
    behavior: merge
    envs:
      - environment
      
patches:
- ingressPatch.yaml
- prodConfigPatch.yaml
- resourcesPatch.yaml
- replicasPatch.yaml
- hpaPatch.yaml
- priorityPatch.yaml
