apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-ingress
  annotations:
    kubernetes.io/ingress.class: "kong"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    # reference production issuer
    cert-manager.io/cluster-issuer: "letsencrypt-issuer-kong"
spec:
  tls:
  - hosts:
    - staging-api.alpacasino.io
    secretName: backend-cert-secret
  rules:
  - host: staging-api.alpacasino.io
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: backend
              port:
                number: 80
