name: Deploy to Kubernetes cluster

on: workflow_dispatch

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    outputs:
      image_digest: ${{ steps.docker_build.outputs.digest }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: k8s-setup
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Install node dependencies
        run: npm ci
      - name: Install doctl (to be able to login on Digital Ocean)
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Login to Digital Ocean docker registry
        run: doctl registry login
      - name: Build the docker image
        id: docker_build
        run: echo '::set-output name=digest::'`docker build . -q -t registry.digitalocean.com/wallfair/backend_k8s`
      - name: Publish the docker image to Digital Ocean
        run: docker push registry.digitalocean.com/wallfair/backend_k8s
  
  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: k8s-setup
      - name: echo inputs debug
        run: echo ${{ needs.build_and_push.outputs.image_digest }}
      - name: Set up Kustomize
        run: curl -sfLo kustomize.tar.gz https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv4.4.0/kustomize_v4.4.0_linux_amd64.tar.gz && tar zxf kustomize.tar.gz
      - name: Edit deployment image
        run: ./kustomize edit image registry.digitalocean.com/wallfair/backend_k8s@${{ needs.build_and_push.outputs.image_digest }}
        working-directory: ./infra/environments/staging
      - uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.K8S_CONFIG_TEST }}
        with:
          args: apply -k infra/environments/staging
  
