name: Deploy to Kubernetes cluster

on: workflow_dispatch

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: k8s-setup
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Install node dependencies
        run: npm ci
      - name: Install doctl (to be able to login on Digital Ocean)
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Login to Digital Ocean docker registry
        run: doctl registry login
      - name: Build the docker image
        run: docker build . -t registry.digitalocean.com/wallfair/backend-k8s:${{ github.event.inputs.version }}
      - name: Publish the docker image to Digital Ocean
        run: docker push registry.digitalocean.com/wallfair/backend-k8s:${{ github.event.inputs.version }}
  
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.K8S_CONFIG_TEST }}
        with:
          args: apply -f infra
  
